export const nodeColors: { [char: string]: string } = {
  prompts: "#4367BF",
  llms: "#6344BE",
  chains: "#FE7500",
  agents: "#903BBE",
  tools: "#FF3434",
  memories: "#FF9135",
  advanced: "#000000",
  chat: "#454173",
  thought: "#272541",
  docloaders: "#FF9135",
  toolkits: "#DB2C2C",
  wrappers: "#E6277A",
  unknown: "#9CA3AF",
};

export const nodeNames: { [char: string]: string } = {
  prompts: "Prompts",
  llms: "LLMs",
  chains: "Chains",
  agents: "Agents",
  tools: "Tools",
  memories: "Memories",
  advanced: "Advanced",
  chat: "Chat",
  docloaders: "Document Loader",
  toolkits: "Toolkits",
  wrappers: "Wrappers",
  unknown: "Unknown",
};
